plugins {
    alias(libs.plugins.spring.boot)
}

dependencies {
    implementation project(':common')
    implementation libs.spring.boot.starter.web
    implementation libs.spring.boot.starter.data.jpa
    implementation libs.spring.boot.starter.mail
    implementation libs.spring.kafka
    implementation libs.spring.boot.starter.actuator
    implementation libs.flyway.core
    implementation libs.flyway.postgresql
    runtimeOnly libs.postgresql
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    testImplementation libs.spring.boot.starter.test
    testImplementation libs.spring.kafka.test
    testImplementation libs.testcontainers.junit
    testImplementation libs.testcontainers.postgresql
    testImplementation libs.testcontainers.kafka
}
