server:
  port: 8081

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/catalog_db
    username: ${POSTGRES_USER:flashsale}
    password: ${POSTGRES_PASSWORD:flashsale}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
